from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol


_MAX_FIELD = 200
_MAX_SECRET = 8192


def _clean_identifier(value: str, field: str) -> str:
    if not isinstance(value, str):
        raise TypeError(f"{field} must be a string")
    cleaned = value.strip()
    if not cleaned or len(cleaned) > _MAX_FIELD:
        raise ValueError(f"{field} must be 1..{_MAX_FIELD} characters")
    if any(ch.isspace() for ch in cleaned):
        raise ValueError(f"{field} must not contain whitespace")
    return cleaned


@dataclass(frozen=True)
class CredentialRef:
    """Non-secret pointer to one account-scoped credential."""

    platform: str
    account_id: str
    secret_name: str

    def __post_init__(self) -> None:
        object.__setattr__(self, "platform", _clean_identifier(self.platform, "platform").lower())
        object.__setattr__(self, "account_id", _clean_identifier(self.account_id, "account_id"))
        object.__setattr__(self, "secret_name", _clean_identifier(self.secret_name, "secret_name"))


class CredentialLease:
    """Short-lived in-memory secret value with redacted display semantics.

    The lease is deliberately not a dataclass so its value is never exposed by an
    autogenerated repr. Callers must explicitly reveal the secret at the narrow
    transport boundary that needs it.
    """

    __slots__ = ("_value",)

    def __init__(self, value: str) -> None:
        if not isinstance(value, str):
            raise TypeError("credential value must be a string")
        if not value or len(value) > _MAX_SECRET or any(ch in "\r\n" for ch in value):
            raise ValueError("credential value is missing or malformed")
        self._value = value

    def reveal(self) -> str:
        return self._value

    def __repr__(self) -> str:
        return "CredentialLease(<redacted>)"

    def __str__(self) -> str:
        return "<redacted>"


class CredentialProvider(Protocol):
    """Minimal provider contract; implementations may use env, OS vaults or cloud KMS."""

    def lease(self, ref: CredentialRef) -> CredentialLease:
        ...


def lease_credential(provider: CredentialProvider, ref: CredentialRef) -> CredentialLease:
    """Resolve one credential fail closed without persisting or copying it into state."""

    if not isinstance(ref, CredentialRef):
        raise TypeError("ref must be a CredentialRef")
    lease_fn = getattr(provider, "lease", None)
    if not callable(lease_fn):
        raise TypeError("provider must implement lease(ref)")
    lease = lease_fn(ref)
    if not isinstance(lease, CredentialLease):
        raise TypeError("credential provider returned an invalid lease")
    return lease
